import{a as L,S as w,i as s}from"./assets/vendor-DnoGfDwQ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();async function u(a,e=1){return(await L.get("https://pixabay.com/api/",{params:{key:"55626104-ba3f0d0514f6dfab3319c84ea",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),P=new w(".gallery a",{captionsData:"alt",captionDelay:250});function g(a){const e=a.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
          <div class="info">
            <div class="info-item"><b>Likes</b><span>${r.likes}</span></div>
            <div class="info-item"><b>Views</b><span>${r.views}</span></div>
            <div class="info-item"><b>Comments</b><span>${r.comments}</span></div>
            <div class="info-item"><b>Downloads</b><span>${r.downloads}</span></div>
          </div>
        </a>
      </li>`).join("");f.insertAdjacentHTML("beforeend",e),P.refresh()}function S(){f.innerHTML=""}function y(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function b(){h.classList.remove("hidden")}function v(){h.classList.add("hidden")}let n=1,l="";const q=document.querySelector(".load-more"),d=document.querySelector(".form");d.addEventListener("submit",async a=>{if(a.preventDefault(),l=a.currentTarget.elements["search-text"].value.trim(),l===""){s.warning({message:"Please fill in the search field!"});return}n=1,v(),S(),y();try{const e=await u(l,n);if(e.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(e.hits),Math.ceil(e.totalHits/15)>1?b():s.info({message:"You've reached the end of search results."})}catch(e){s.error({message:"Something went wrong. Please try again later."}),console.error(e)}finally{p(),d.reset()}});q.addEventListener("click",async()=>{n+=1,y(),v();try{const a=await u(l,n);g(a.hits);const e=Math.ceil(a.totalHits/15);n>=e?s.info({message:"We're sorry, but you've reached the end of search results."}):b();const r=document.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}catch{s.error({message:"Error loading more images!"})}finally{p()}});
//# sourceMappingURL=index.js.map
