import{a as v,S as L,i as o}from"./assets/vendor-DnoGfDwQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();async function u(s,t=1){return(await v.get("https://pixabay.com/api/",{params:{key:"55626104-ba3f0d0514f6dfab3319c84ea",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),b=new L(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const t=s.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
          <div class="info">
            <div class="info-item"><b>Likes</b><span>${r.likes}</span></div>
            <div class="info-item"><b>Views</b><span>${r.views}</span></div>
            <div class="info-item"><b>Comments</b><span>${r.comments}</span></div>
            <div class="info-item"><b>Downloads</b><span>${r.downloads}</span></div>
          </div>
        </a>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),b.refresh()}function w(){m.innerHTML=""}function p(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}let i=1,c="";const n=document.querySelector(".load-more"),f=document.querySelector(".form");f.addEventListener("submit",async s=>{if(s.preventDefault(),c=s.currentTarget.elements["search-text"].value.trim(),c===""){o.warning({message:"Please fill in the search field!"});return}i=1,n.classList.add("hidden"),w(),p();try{const t=await u(c,i);if(t.hits.length===0){o.error({message:"Sorry, no images found!"});return}h(t.hits),t.totalHits>15&&n.classList.remove("hidden")}catch{o.error({message:"Error fetching images!"})}finally{y(),f.reset()}});n.addEventListener("click",async()=>{i+=1,p(),n.classList.add("hidden");try{const s=await u(c,i);h(s.hits);const t=Math.ceil(s.totalHits/15);i>=t?o.info({message:"You've reached the end of search results."}):n.classList.remove("hidden");const r=document.querySelector(".gallery-item");if(r){const l=r.getBoundingClientRect().height;window.scrollBy({top:l*2,behavior:"smooth"})}}catch{o.error({message:"Error loading more images!"})}finally{y()}});
//# sourceMappingURL=index.js.map
